const modules = import.meta.glob('./assets/icons/*.svg', {
  eager: true,
  query: '?raw',
})

export const iconRegistry: Record<string, string> = Object.entries(modules).reduce(
  (registry, [path, module]) => {
    const key = path
      .split('/')
      .pop()! // e.g., "Access.svg"
      .replace('.svg', '') // -> "Access"
      .toLowerCase() // -> "access"

    registry[key] = (module as { default: string }).default
    return registry
  },
  {} as Record<string, string>,
)

// Export an array of all available icon names
export const iconNames = Object.keys(iconRegistry) as IconTitle[]

export type IconTitle =
  | 'access'
  | 'arrow down'
  | 'arrow up'
  | 'account'
  | 'archive'
  | 'assign'
  | 'alert'
  | 'bed'
  | 'behaviour'
  | 'calendar'
  | 'call'
  | 'cancel'
  | 'chat'
  | 'check'
  | 'connect'
  | 'clock'
  | 'cognition'
  | 'collapse'
  | 'communication'
  | 'community & recreation'
  | 'continence'
  | 'continue'
  | 'create'
  | 'daily living & environment'
  | 'delete'
  | 'directory'
  | 'discard'
  | 'disconnect'
  | 'document'
  | 'dragindicator'
  | 'download'
  | 'dropdown'
  | 'duplicate'
  | 'edit'
  | 'education & employment'
  | 'email'
  | 'expand'
  | 'explore'
  | 'failure'
  | 'favourite'
  | 'filter'
  | 'hamburger'
  | 'help'
  | 'hide'
  | 'home'
  | 'hourglass'
  | 'hyperlink'
  | 'information'
  | 'list plus'
  | 'loading'
  | 'location'
  | 'media'
  | 'medication & healthcare'
  | 'mental health'
  | 'minus'
  | 'mobility & physical'
  | 'more options'
  | 'move'
  | 'next'
  | 'notifications'
  | 'nutrition & hydration'
  | 'organisation'
  | 'person'
  | 'personal care & hygiene'
  | 'photo'
  | 'plus'
  | 'previous'
  | 'printer'
  | 'private'
  | 'pws'
  | 'recent'
  | 'religious & spiritual identity'
  | 'reload'
  | 'reorder'
  | 'room mapping'
  | 'saved items'
  | 'search'
  | 'security'
  | 'sensory'
  | 'service'
  | 'settings'
  | 'sexuality & relationships'
  | 'share'
  | 'skin integrity'
  | 'sleep & rest'
  | 'sort a-z'
  | 'sort z-a'
  | 'sparkle'
  | 'specific diagnosis & long-term conditions'
  | 'status'
  | 'submit'
  | 'success'
  | 'sync'
  | 'target'
  | 'thumbs up'
  | 'thumbs down'
  | 'unarchive'
  | 'unassign'
  | 'unlock'
  | 'upload'
  | 'view'
  | 'voice input'
  | 'warning circle'
  | 'x mark'
